In [1]:
# Import Dependencies
import tensorflow as tf

In [5]:
# Expand Dims Method
a = tf.constant([1, 2, 3, 4, 5])
print(a.shape)
print(tf.expand_dims(a, axis=0))
print(tf.expand_dims(a, axis=1))

(5,)
tf.Tensor([[1 2 3 4 5]], shape=(1, 5), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]
 [4]
 [5]], shape=(5, 1), dtype=int32)


In [12]:
# Expand Dims On Multi-Dimensional Inputs
a = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [6, 7, 8, 9]
])
print(a.shape)
print(tf.expand_dims(a, axis=0))
print(tf.expand_dims(a, axis=1))
print(tf.expand_dims(a, axis=2))
print(tf.expand_dims(a, axis=-1))

(4, 4)
tf.Tensor(
[[[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]
  [6 7 8 9]]], shape=(1, 4, 4), dtype=int32)
tf.Tensor(
[[[1 2 3 4]]

 [[2 3 4 5]]

 [[3 4 5 6]]

 [[6 7 8 9]]], shape=(4, 1, 4), dtype=int32)
tf.Tensor(
[[[1]
  [2]
  [3]
  [4]]

 [[2]
  [3]
  [4]
  [5]]

 [[3]
  [4]
  [5]
  [6]]

 [[6]
  [7]
  [8]
  [9]]], shape=(4, 4, 1), dtype=int32)
tf.Tensor(
[[[1]
  [2]
  [3]
  [4]]

 [[2]
  [3]
  [4]
  [5]]

 [[3]
  [4]
  [5]
  [6]]

 [[6]
  [7]
  [8]
  [9]]], shape=(4, 4, 1), dtype=int32)


In [38]:
# Squeeze Method
a = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [6, 7, 8, 9]
])
c = tf.expand_dims(a, axis=0)
print(c.shape)
print(tf.squeeze(c, axis=None))
print(tf.squeeze(c, axis=0))

(1, 4, 4)
tf.Tensor(
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [6 7 8 9]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [6 7 8 9]], shape=(4, 4), dtype=int32)


In [24]:
# Reshape Method
a = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(tf.reshape(a, [3, 3]))
print(tf.reshape(a, [3, 3, 1]))
# print(tf.reshape(a, [3, 2, 1])) -> Error : Number of Elements Remain Same
print(tf.reshape(a, [3, -1])) # -> Put -1 on the axis you don't know about and tf will figure it out automatically

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]], shape=(3, 3, 1), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [27]:
# Reshape On Multi-Dimensional Inputs
a = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [6, 7, 8, 9]
])
print(tf.reshape(a, [8, 2]))

tf.Tensor(
[[1 2]
 [3 4]
 [2 3]
 [4 5]
 [3 4]
 [5 6]
 [6 7]
 [8 9]], shape=(8, 2), dtype=int32)


In [37]:
# Concat Method
a = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [6, 7, 8, 9]
])
b = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5]
])
print(a.shape, b.shape)
print(tf.concat([a, b], axis=0)) # -> Here axis 1 has 4 in both tensors, so concat successfull
# print(tf.concat([a, b], axis=1)) -> Error : The other axes must be of same shape
print(a.shape, tf.transpose(b).shape)
print(tf.concat([a, tf.linalg.matrix_transpose(b)], axis=1))
print(tf.concat([a, tf.linalg.matrix_transpose(b)], axis=-1))

(4, 4) (2, 4)
tf.Tensor(
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [6 7 8 9]
 [1 2 3 4]
 [2 3 4 5]], shape=(6, 4), dtype=int32)
(4, 4) (4, 2)
tf.Tensor(
[[1 2 3 4 1 2]
 [2 3 4 5 2 3]
 [3 4 5 6 3 4]
 [6 7 8 9 4 5]], shape=(4, 6), dtype=int32)
tf.Tensor(
[[1 2 3 4 1 2]
 [2 3 4 5 2 3]
 [3 4 5 6 3 4]
 [6 7 8 9 4 5]], shape=(4, 6), dtype=int32)


In [45]:
# Stack Method -> Stacks a list of rank-R Tensors into one rank-(R+1) Tensor
a = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [6, 7, 8, 9]
])
b = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [6, 7, 8, 9]
])
print(a.shape, b.shape) # -> Shapes of both tensors must be same
print(tf.stack([a, b], axis=0)) # -> Similar to Concat Method but adds an extra dimension
print(tf.stack([a, b], axis=1))
print(tf.stack([a, b], axis=-1))

(4, 4) (4, 4)
tf.Tensor(
[[[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]
  [6 7 8 9]]

 [[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]
  [6 7 8 9]]], shape=(2, 4, 4), dtype=int32)
tf.Tensor(
[[[1 2 3 4]
  [1 2 3 4]]

 [[2 3 4 5]
  [2 3 4 5]]

 [[3 4 5 6]
  [3 4 5 6]]

 [[6 7 8 9]
  [6 7 8 9]]], shape=(4, 2, 4), dtype=int32)
tf.Tensor(
[[[1 1]
  [2 2]
  [3 3]
  [4 4]]

 [[2 2]
  [3 3]
  [4 4]
  [5 5]]

 [[3 3]
  [4 4]
  [5 5]
  [6 6]]

 [[6 6]
  [7 7]
  [8 8]
  [9 9]]], shape=(4, 4, 2), dtype=int32)


In [54]:
# Pad Method -> Pads a tensor with a given value
a = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [6, 7, 8, 9]
])
paddings = tf.constant([
    [1, 2], # [PaddingLayersTop, PaddingLayersBottom]
    [2, 3] # [PaddingLayersLeft, PaddingLayersRight]
])
# Padding Modes : CONSTANT -> Constant Value, REFLECT -> Values From The Tensor, SYMMETRIC -> Values From The Tensor
print(tf.pad(a, paddings, "CONSTANT", constant_values=20)) # constant_values defaults to 0
print(tf.pad(a, paddings, "REFLECT"))
print(tf.pad(a, paddings, "SYMMETRIC"))

tf.Tensor(
[[20 20 20 20 20 20 20 20 20]
 [20 20  1  2  3  4 20 20 20]
 [20 20  2  3  4  5 20 20 20]
 [20 20  3  4  5  6 20 20 20]
 [20 20  6  7  8  9 20 20 20]
 [20 20 20 20 20 20 20 20 20]
 [20 20 20 20 20 20 20 20 20]], shape=(7, 9), dtype=int32)
tf.Tensor(
[[4 3 2 3 4 5 4 3 2]
 [3 2 1 2 3 4 3 2 1]
 [4 3 2 3 4 5 4 3 2]
 [5 4 3 4 5 6 5 4 3]
 [8 7 6 7 8 9 8 7 6]
 [5 4 3 4 5 6 5 4 3]
 [4 3 2 3 4 5 4 3 2]], shape=(7, 9), dtype=int32)
tf.Tensor(
[[2 1 1 2 3 4 4 3 2]
 [2 1 1 2 3 4 4 3 2]
 [3 2 2 3 4 5 5 4 3]
 [4 3 3 4 5 6 6 5 4]
 [7 6 6 7 8 9 9 8 7]
 [7 6 6 7 8 9 9 8 7]
 [4 3 3 4 5 6 6 5 4]], shape=(7, 9), dtype=int32)


In [67]:
# Gather Method
a = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [6, 7, 8, 9]
])
print(a.shape)
print(tf.gather(a, [2, 1], axis=0)) # -> Gather Elements Based On Order Specified
print(tf.gather(a, [2, 1], axis=1))
print(tf.gather(a, [[1, 2], [0, 3]], axis=0))

(4, 4)
tf.Tensor(
[[3 4 5 6]
 [2 3 4 5]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[3 2]
 [4 3]
 [5 4]
 [8 7]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[[2 3 4 5]
  [3 4 5 6]]

 [[1 2 3 4]
  [6 7 8 9]]], shape=(2, 2, 4), dtype=int32)


In [72]:
# Gather ND Method -> Gather Accross Multiple Axes At Once
a = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [6, 7, 8, 9]
])
print(tf.gather_nd(a, [[1, 2], [0, 1]]))
print("\n")
# See The Difference
print(tf.gather(a, [[1, 2], [0, 1]], axis=0))
print(tf.gather_nd(a, [[1, 2], [0, 1]]))

tf.Tensor([4 2], shape=(2,), dtype=int32)


tf.Tensor(
[[[2 3 4 5]
  [3 4 5 6]]

 [[1 2 3 4]
  [2 3 4 5]]], shape=(2, 2, 4), dtype=int32)
tf.Tensor([4 2], shape=(2,), dtype=int32)
