In [1]:
# Import Dependencies
import tensorflow as tf

In [7]:
# Matrix Multiplication Method
a = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [6, 7, 8, 9]
])
b = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [6, 7, 8, 9]
])
print(a.shape, b.shape)
print(tf.linalg.matmul(a, b))
print(a@b) # Another Sytax For Mat Mul

(4, 4) (4, 4)
tf.Tensor(
[[ 38  48  58  68]
 [ 50  64  78  92]
 [ 62  80  98 116]
 [ 98 128 158 188]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[ 38  48  58  68]
 [ 50  64  78  92]
 [ 62  80  98 116]
 [ 98 128 158 188]], shape=(4, 4), dtype=int32)


In [17]:
# Transpose Method -> Rows <=> Columns
a = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [6, 7, 8, 9]
])
b = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5]
])
print(a.shape, b.shape)
print(tf.transpose(a)) # or print(tf.linalg.matrix_transpose(a))
print(tf.transpose(b))

(4, 4) (2, 4)
tf.Tensor(
[[1 2 3 6]
 [2 3 4 7]
 [3 4 5 8]
 [4 5 6 9]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[1 2]
 [2 3]
 [3 4]
 [4 5]], shape=(4, 2), dtype=int32)


In [18]:
# Some Arguments Of MatMul Method
a = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [6, 7, 8, 9]
])
b = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5]
])
a@tf.transpose(b)
# Can Also Be Written As
print(tf.linalg.matmul(a, b, transpose_a=False, transpose_b=True))

tf.Tensor(
[[ 30  40]
 [ 40  54]
 [ 50  68]
 [ 80 110]], shape=(4, 2), dtype=int32)


In [23]:
# 3-Dimensional Tensor Matrix Multiplication
a = tf.constant([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [4, 5],
        [3, 7]
    ],
    [
        [2, 8],
        [1, 6]
    ],
    [
        [2, 6],
        [2, 7]
    ]

])
b = tf.constant([
    [
        [1, 2, 3],
        [3, 4, 5]
    ],
    [
        [4, 5, 6],
        [3, 7, 4]
    ],
    [
        [2, 8, 5],
        [1, 6, 5]
    ],
    [
        [2, 6, 5],
        [2, 7, 4]
    ]

])
print(a.shape, b.shape)
print(tf.linalg.matmul(a, b)) # Block Wise MatMul -> 4 * ((2, 2)*(2*3))

# To Verify
a[0]@b[0]


(4, 2, 2) (4, 2, 3)
tf.Tensor(
[[[ 7 10 13]
  [15 22 29]]

 [[31 55 44]
  [33 64 46]]

 [[12 64 50]
  [ 8 44 35]]

 [[16 54 34]
  [18 61 38]]], shape=(4, 2, 3), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7, 10, 13],
       [15, 22, 29]], dtype=int32)>

In [31]:
# Band Part Method -> Copy A Tensor Setting Everything Outside A Central Band In Each Innermost Matrix To Zero
a = tf.constant([
    [1, 2, 3],
    [2, 3, 4],
    [3, 4, 5]
])
print(tf.linalg.band_part(a, num_lower=1, num_upper=1))

# m, n are element positions
# if (num_lower<0 or (m-n)<=num_lower) and (num_upper<0 or (n-m)<=num_upper): Value Maintained 
# else: Zero

tf.Tensor(
[[1 2 0]
 [2 3 4]
 [0 4 5]], shape=(3, 3), dtype=int32)


In [33]:
# Special Cases of Band Part
print(tf.linalg.band_part(a, num_lower=0, num_upper=0)) # Diagonal Part
print(tf.linalg.band_part(a, num_lower=0, num_upper=-1)) # Upper Triangular Part
print(tf.linalg.band_part(a, num_lower=-1, num_upper=0)) # Lower Triangular Part

tf.Tensor(
[[1 0 0]
 [0 3 0]
 [0 0 5]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [0 3 4]
 [0 0 5]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 0 0]
 [2 3 0]
 [3 4 5]], shape=(3, 3), dtype=int32)


In [37]:
# Determinant Method -> Of Square Matrix Only
a = tf.constant([
    [1, 2],
    [2, 5],
], dtype=tf.float32)
tf.linalg.det(a)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [41]:
# Inverse Method -> Only On Full-Rank Matrix
# A*A^-1 = I
a = tf.constant([
    [1, 2, 3],
    [2, 5, 4],
    [3, 4, 5]
], dtype=tf.float32)
tf.linalg.inv(a)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.1250002 , -0.25      ,  0.8750001 ],
       [-0.24999997,  0.5       , -0.25000003],
       [ 0.87500006, -0.25      , -0.12500003]], dtype=float32)>

In [77]:
# Mat Mul Using Einsum Method -> Sperate Tensor Shapes by , and Seperate Output by ->
a = tf.constant([
    [1, 2, 3],
    [2, 3, 4],
    [3, 4, 5],
    [6, 7, 8]
])
b = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [2, 6, 4, 5]
])
print(a.shape, b.shape)
print((a@b).shape) # (i, j) * (j, k) => (i, k)
tf.einsum("ij, jk->ik", a, b)

(4, 3) (3, 4)
(4, 4)


<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[11, 26, 23, 29],
       [16, 37, 34, 43],
       [21, 48, 45, 57],
       [36, 81, 78, 99]], dtype=int32)>

In [56]:
# Inner Product Using Einsum Method
a = tf.constant([2, 6, 5, 2])
b = tf.constant([0, 1, 3, 2])
print(tf.einsum("i,i->", a, b))
tf.einsum("i,i->i", a, b)

tf.Tensor(25, shape=(), dtype=int32)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 0,  6, 15,  4], dtype=int32)>

In [65]:
# Outer Product Using Einsum Method -> transpose(a)*b
a = tf.constant([2, 6, 5, 2])
b = tf.constant([0, 1, 3, 2, 4, 5])
print(tf.einsum("i,j->ij", a, b))
print(tf.einsum("i,j->", a, b))
print(tf.reduce_sum(tf.einsum("i,j->ij", a, b)))

tf.Tensor(
[[ 0  2  6  4  8 10]
 [ 0  6 18 12 24 30]
 [ 0  5 15 10 20 25]
 [ 0  2  6  4  8 10]], shape=(4, 6), dtype=int32)
tf.Tensor(225, shape=(), dtype=int32)
tf.Tensor(225, shape=(), dtype=int32)


In [71]:
# Transpose Using Einsum Method
b = tf.constant([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [2, 6, 4, 5]
])
tf.einsum("ij->ji", b)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 2, 2],
       [2, 3, 6],
       [3, 4, 4],
       [4, 5, 5]], dtype=int32)>

In [73]:
# Element-Wise Multiplication Using Einsum Method
a = tf.constant([
    [1, 2, 3],
    [2, 3, 4],
    [3, 4, 5]
])
b = tf.constant([
    [1, 2, 3],
    [2, 3, 4],
    [2, 6, 4]
])
tf.einsum("ij,ij->ij", a, b)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [ 4,  9, 16],
       [ 6, 24, 20]], dtype=int32)>

In [78]:
# Using Einsum Method on 3-D Tensors
a = tf.constant([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [4, 5],
        [3, 7]
    ],
    [
        [2, 8],
        [1, 6]
    ],
    [
        [2, 6],
        [2, 7]
    ]

])
b = tf.constant([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [4, 5],
        [3, 7]
    ],
    [
        [2, 8],
        [1, 6]
    ],
    [
        [2, 6],
        [2, 7]
    ]

])
print(a.shape, b.shape)
print(tf.einsum("bij,bjk->bik", a, b))

(4, 2, 2) (4, 2, 2)
tf.Tensor(
[[[ 7 10]
  [15 22]]

 [[31 55]
  [33 64]]

 [[12 64]
  [ 8 44]]

 [[16 54]
  [18 61]]], shape=(4, 2, 2), dtype=int32)


In [87]:
# A*Transpose(A) using Einsum Method
a = tf.constant([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [4, 5],
        [3, 7]
    ],
    [
        [2, 8],
        [1, 6]
    ],
    [
        [2, 6],
        [2, 7]
    ]

])
tf.einsum("bij,bkj->bik", a, a)

<tf.Tensor: shape=(4, 2, 2), dtype=int32, numpy=
array([[[ 5, 11],
        [11, 25]],

       [[41, 47],
        [47, 58]],

       [[68, 50],
        [50, 37]],

       [[40, 46],
        [46, 53]]], dtype=int32)>