In [1]:
# Import Dependencies
import tensorflow as tf

In [7]:
# Absolute Function
x = tf.constant(-0.2)
x2D = tf.constant([0, 1, 2, -3, -4])
xComplex = tf.constant(2+3j)
print(tf.abs(x))
print(tf.abs(x2D))
print(tf.abs(xComplex))
tf.sqrt(2.0**2 + 3.0**2)

tf.Tensor(0.2, shape=(), dtype=float32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor(3.605551275463989, shape=(), dtype=float64)


<tf.Tensor: shape=(), dtype=float32, numpy=3.6055512>

In [17]:
# Element-Wise Addition/Subtraction/Multiply/Divide Method
x = tf.constant([2, 3, 5, 7])
y = tf.constant([7, 7, 2, 1])
scalar = tf.constant(1)
zeroScalar = tf.constant(0)
print(tf.add(x, y))
print(tf.add(x, scalar))
print(tf.subtract(x, y))
print(tf.multiply(x, y))
print(tf.divide(x, y))
print(tf.divide(x, zeroScalar))
print(tf.math.divide_no_nan(x, zeroScalar))

tf.Tensor([ 9 10  7  8], shape=(4,), dtype=int32)
tf.Tensor([3 4 6 8], shape=(4,), dtype=int32)
tf.Tensor([-5 -4  3  6], shape=(4,), dtype=int32)
tf.Tensor([14 21 10  7], shape=(4,), dtype=int32)
tf.Tensor([0.28571429 0.42857143 2.5        7.        ], shape=(4,), dtype=float64)
tf.Tensor([inf inf inf inf], shape=(4,), dtype=float64)
tf.Tensor([0. 0. 0. 0.], shape=(4,), dtype=float64)


In [32]:
# Shape Broadcasting For Element-Wise Operations
x = tf.constant([2, 3, 4, 5])
y = tf.constant([
    [1],
    [3]
])
print(tf.math.multiply(x, y))

tf.Tensor(
[[ 2  3  4  5]
 [ 6  9 12 15]], shape=(2, 4), dtype=int32)


In [20]:
# Maximum/Minimum Function
x = tf.constant([1, 2, 3, 4])
y = tf.constant([0, -2, 3, 5])
print(tf.maximum(x, y))
print(tf.minimum(x, y))

tf.Tensor([1 2 3 5], shape=(4,), dtype=int32)
tf.Tensor([ 0 -2  3  4], shape=(4,), dtype=int32)


In [31]:
# Argmax/Argmin Method -> Index of Maximum/Minimum Value
A = tf.constant([2, 20, 30, 3, 6])
print(tf.argmax(A))
print(tf.argmin(A))

A2D = tf.constant([
    [3, 1, 9, 6, 5],
    [0, 1, 7, 3, 2],
    [1, 5, 1, 2, 0],
    [7, 3, 0, 9, 0]
])
print(tf.math.argmax(A2D, axis=0)) # axis 0/1 => accross rows/columns . Defaults to axis=0
print(tf.math.argmax(A2D, axis=1)) 

tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([3 2 0 3 0], shape=(5,), dtype=int64)
tf.Tensor([2 2 1 3], shape=(4,), dtype=int64)


In [33]:
# Equal Method -> True/False on Element-Wise Comparison
x = tf.constant([1, 2, 3, 4])
y = tf.constant([1, 3, 4, 4])
print(tf.equal(x, y))

tf.Tensor([ True False False  True], shape=(4,), dtype=bool)


In [34]:
# Power Method
x = tf.constant([
    [2, 2],
    [3, 3]
])
y = tf.constant([
    [0, 1],
    [2, 3]
])
print(tf.pow(x, y))

tf.Tensor(
[[ 1  2]
 [ 9 27]], shape=(2, 2), dtype=int32)


In [47]:
# Reduce Methods
x = tf.constant([5, 1, 2, 4])
print(tf.math.reduce_max(x, axis=None, keepdims=False, name=None))
print(tf.math.reduce_sum(x, axis=None, keepdims=False, name=None))
print(tf.math.reduce_max(x, axis=None, keepdims=True, name=None))
print(tf.math.reduce_sum(x, axis=None, keepdims=True, name=None))

print("\n")

x2D = tf.constant([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print(tf.math.reduce_sum(x2D, axis=None, keepdims=False, name=None))
print(tf.math.reduce_sum(x2D, axis=None, keepdims=True, name=None))
print(tf.math.reduce_sum(x2D, axis=0, keepdims=False, name=None))
print(tf.math.reduce_sum(x2D, axis=1, keepdims=False, name=None))
print(tf.math.reduce_sum(x2D, axis=1, keepdims=True, name=None))

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor([5], shape=(1,), dtype=int32)
tf.Tensor([12], shape=(1,), dtype=int32)


tf.Tensor(78, shape=(), dtype=int32)
tf.Tensor([[78]], shape=(1, 1), dtype=int32)
tf.Tensor([15 18 21 24], shape=(4,), dtype=int32)
tf.Tensor([10 26 42], shape=(3,), dtype=int32)
tf.Tensor(
[[10]
 [26]
 [42]], shape=(3, 1), dtype=int32)


In [52]:
# Top-K Methods
x = tf.constant([1, 2, 98, 99, 100, 3, 1, 4, 5])
print(tf.math.top_k(x, k=5))

TopKV2(values=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([100,  99,  98,   5,   4], dtype=int32)>, indices=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 3, 2, 8, 7], dtype=int32)>)


In [60]:
# Sigmoid Function -> Sigmoid(x) = 1/(1+exp(-x)) -> Range(0, 1)
x = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
print(tf.math.sigmoid(x))

tf.Tensor([0.7310586  0.880797   0.95257413 0.98201376 0.9933072 ], shape=(5,), dtype=float32)
