In [2]:
# Import Dependencies
import tensorflow as tf

In [ ]:
# Tensor Indexing -> Access Each Element Of Tensor
tensorIndexed = tf.constant([2, 4, 9, 0, 4, 5, 6, 7])
print(tensorIndexed[0])
print(tensorIndexed[3])
print(tensorIndexed[-1])

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


In [16]:
# Tensor Slicing -> Pick A Range From Tensor With/Without Steps [start : end : step]
print(tensorIndexed[1:6])
print(tensorIndexed[:6])
print(tensorIndexed[3:])
print(tensorIndexed[3:-1])
print(tensorIndexed[::-1])
print(tensorIndexed[1:7:2])

tf.Tensor([4 9 0 4 5], shape=(5,), dtype=int32)
tf.Tensor([2 4 9 0 4 5], shape=(6,), dtype=int32)
tf.Tensor([0 4 5 6 7], shape=(5,), dtype=int32)
tf.Tensor([0 4 5 6], shape=(4,), dtype=int32)
tf.Tensor([7 6 5 4 0 9 4 2], shape=(8,), dtype=int32)
tf.Tensor([4 0 5], shape=(3,), dtype=int32)


In [30]:
# Indexing & Slicing On Multi-Dimensional Tensors
tensorIndexed2D = tf.constant([
    [2, 3, 4, 5, 6],
    [3, 4, 1, 3, 6],
    [2, 4, 5, 6, 7]
])
print(tensorIndexed2D[1][0])
print(tensorIndexed2D[1, 0])
print(tensorIndexed2D[1, -1])
print(tensorIndexed2D[-1, -1])
print("\n")
print(tensorIndexed2D[1, 2:4])
print(tensorIndexed2D[0:2, 1])
print(tensorIndexed2D[0, ...]) # Shape (5, )
print(tensorIndexed2D[0:1, ...]) # Shape (1, 5)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


tf.Tensor([1 3], shape=(2,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)
tf.Tensor([[2 3 4 5 6]], shape=(1, 5), dtype=int32)
