In [1]:
# Import Dependencies
import tensorflow as tf

# Ragged Tensors

In [7]:
# Ragged Tensors
a = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(a, "\n")

# But code below will give error
    # a = tf.constant([
    #     [1, 2],
    #     [4, 5, 6],
    #     [7]
    # ])
    # print(a)

# But in some cases you need such type of data with inconsistent shapes across an axis -> Use Ragged Tensors

raggedA = tf.ragged.constant([
    [1, 2],
    [4, 5, 6],
    [7]
])
print(raggedA)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32) 

<tf.RaggedTensor [[1, 2], [4, 5, 6], [7]]>


# Ragged Tensor Methods

In [20]:
# Boolean Mask -> Masks a ragged tensor
raggedAConstant = tf.ragged.constant([
    [1, 2],
    [4, 5, 6],
    [7]
])
raggedABooleanMask = tf.ragged.boolean_mask(
    raggedAConstant,
    tf.ragged.constant([[False, True], [False, True, True], [True]])
)
print(raggedABooleanMask)

<tf.RaggedTensor [[2], [5, 6], [7]]>


In [26]:
# RaggedTensor.rowMethods

# Row-Splits -> [0, 4, 4, 7, 8, 8] => [[0:4], [4:4], [4:7], [7:8], [8:8]]
values = [3, 1, 4, 1, 5, 9, 2, 6]
print(tf.RaggedTensor.from_row_splits(values, row_splits=[0, 4, 4, 7, 8, 8]))

# Row-Lengths -> [4, 0, 3, 1, 0] => First 4, then, next 0, then, next 3, and so on ....
values = [3, 1, 4, 1, 5, 9, 2, 6]
print(tf.RaggedTensor.from_row_lengths(values, row_lengths=[4, 0, 3, 1, 0]))

# Value-RowIDS -> [0, 0, 0, 0, 2, 2, 2, 3] => Value-RowIDS[i] => Element value[i] is part of this row value-RowIDS[i]
values = [3, 1, 4, 1, 5, 9, 2, 6]
print(tf.RaggedTensor.from_value_rowids(values, value_rowids=[0, 0, 0, 0, 2, 2, 2, 3]))

# Row-Starts -> [0, 4, 4, 7, 8] => Row starts from rowStarts[i]
values = [3, 1, 4, 1, 5, 9, 2, 6]
print(tf.RaggedTensor.from_row_starts(values, row_starts=[0, 4, 4, 7, 8]))

# Row-Limits -> [4, 4, 7, 8, 8] => Row ends at rowLimits[i]
values = [3, 1, 4, 1, 5, 9, 2, 6]
print(tf.RaggedTensor.from_row_limits(values, row_limits=[4, 4, 7, 8, 8]))

# Uniform-Row-Length => Make rows of uniform lengths
values = [3, 1, 4, 1, 5, 9, 2, 6]
print(tf.RaggedTensor.from_uniform_row_length(values, uniform_row_length=2))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6]]>
<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
<tf.RaggedTensor [[3, 1],
 [4, 1],
 [5, 9],
 [2, 6]]>


# Sparse Tensors

In [32]:
# Sparse Tensor -> Many zeroes as compared to non-zeroes
sparseTensor = tf.sparse.SparseTensor(
    indices=[[0, 0],
             [2, 5]], # On which indexes we have values
    values=[1, 9],  # What are those values
    dense_shape=[5, 6] # Dense Tensor Shape
)
print(sparseTensor)
tf.sparse.to_dense(sparseTensor) # Convert sparse tensor => dense tensor

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 5]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 9], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>

# String Tensors

In [ ]:
# String Tensor
stringTensor = tf.constant(["i am ", "a ", "string"])
print(stringTensor)

tf.Tensor([b'i am ' b'a ' b'string'], shape=(3,), dtype=string)


In [36]:
# String Tensor Join Method -> Element-Wise concatenation of a list of string tensors
stringTensorA = tf.constant(["i am ", "a ", "string"])
stringTensorB = tf.constant(["i am ", "also a  ", "new string"])
print(tf.strings.join(stringTensorA, separator="+"))
print(tf.strings.join([stringTensorA, stringTensorB], separator="+"))

tf.Tensor(b'i am +a +string', shape=(), dtype=string)
tf.Tensor([b'i am +i am ' b'a +also a  ' b'string+new string'], shape=(3,), dtype=string)


# TennsorFlow Variables

In [43]:
# tf-variable
x = tf.constant([1, 2, 3, 4, 5])
xVar = tf.Variable(x)
print(x)
print(xVar)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>


In [47]:
# Modify variable
print(xVar.assign_add([5, 5, 5, 5, 5]))
print(xVar.assign_sub([3, 3, 3, 3, 3]))
print(xVar.assign([5, 5, 5, 5, 5]))

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 8,  9, 10, 11, 12], dtype=int32)>
<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([5, 6, 7, 8, 9], dtype=int32)>
<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([5, 5, 5, 5, 5], dtype=int32)>
