In [38]:
# Import Dependencies
import tensorflow as tf
import numpy as np

In [ ]:
# 0-Dimensional Tensor
tensorZeroD = tf.constant(4)
tensorZeroD

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [40]:
# 1-Dimensional Tensor
tensorOneD = tf.constant([2, 0, -3.3], dtype=tf.float32)
tensorOneD

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2. ,  0. , -3.3], dtype=float32)>

In [41]:
# 2-Dimensional Tensor
tensorTwoD = tf.constant([
    [1, 2, 0],
    [3, 5, -1],
    [1, 5, 6],
    [2, 3, 8]
])
tensorTwoD

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  0],
       [ 3,  5, -1],
       [ 1,  5,  6],
       [ 2,  3,  8]], dtype=int32)>

In [42]:
# 3-Dimensional Tensor
tensorThreeD = tf.constant([
    [
        [1, 2, 3],
        [3, 4, 5]
    ],
    [
        [4, 5, 6],
        [3, 7, 4]
    ],
    [
        [2, 8, 5],
        [1, 6, 5]
    ],
    [
        [2, 6, 5],
        [2, 7, 4]
    ]

])
tensorThreeD

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 4, 5]],

       [[4, 5, 6],
        [3, 7, 4]],

       [[2, 8, 5],
        [1, 6, 5]],

       [[2, 6, 5],
        [2, 7, 4]]], dtype=int32)>

In [ ]:
# Tensor Shape Method
tensorThreeD.shape

TensorShape([4, 2, 3])

In [20]:
# Tensor Casting
floatTensor = tf.constant([1.2, 0.0, 4.8, 5.1], dtype=tf.float32)
intTensor = tf.cast(floatTensor, dtype=tf.int16)
boolTensor = tf.cast(floatTensor, dtype=tf.bool)
print(floatTensor)
print(intTensor)
print(boolTensor)

tf.Tensor([1.2 0.  4.8 5.1], shape=(4,), dtype=float32)
tf.Tensor([1 0 4 5], shape=(4,), dtype=int16)
tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [25]:
# Numpy Array To Tensor
npArray = np.array([1, 2, 3, 4])
print(npArray)

convertedTensor = tf.convert_to_tensor(npArray)
convertedTensor

[1 2 3 4]


<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [30]:
# Eye Method -> Identity Matrix
eyeTensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eyeTensor)
print("\n")
print(3*eyeTensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [33]:
# Rectangle Eye Tensor
rectangleEyeTensor = tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
rectangleEyeTensor

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [37]:
# Batch Shape In Eye Method
batchEyeTensor1 = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2, ],
    dtype=tf.dtypes.float32,
    name=None
)

batchEyeTensor2 = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2, 4],
    dtype=tf.dtypes.float32,
    name=None
)
print(batchEyeTensor1)
print("\n")
print(batchEyeTensor2)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 

In [44]:
# Fill Method
fillTensor = tf.fill(
    [3, 4], 5, name=None
)
fillTensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int32)>

In [48]:
# Ones Method
onesTensor = tf.ones(
    [3, 4],
    dtype=tf.dtypes.float32,
    name=None
)
onesTensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [49]:
# Ones-Like Method
inputTensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])
onesLikeTensor = tf.ones_like(inputTensor)
print(inputTensor)
onesLikeTensor

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [50]:
# Zeroes Method
zeroesTensor = tf.zeros(
    [3, 4],
    dtype=tf.dtypes.int16,
    name=None
)
zeroesTensor

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [51]:
# Zeroes-Like Method
inputTensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])
zeroesLikeTensor = tf.zeros_like(inputTensor)
print(inputTensor)
zeroesLikeTensor

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [52]:
# Rank Method
inputTensor = tf.constant([
    [
        [1, 2, 3],
        [3, 4, 5]
    ],
    [
        [4, 5, 6],
        [3, 7, 4]
    ],
    [
        [2, 8, 5],
        [1, 6, 5]
    ],
    [
        [2, 6, 5],
        [2, 7, 4]
    ]

])
tf.rank(inputTensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [54]:
# Size Method
inputTensor = tf.constant([
    [
        [1, 2, 3],
        [3, 4, 5]
    ],
    [
        [4, 5, 6],
        [3, 7, 4]
    ],
    [
        [2, 8, 5],
        [1, 6, 5]
    ],
    [
        [2, 6, 5],
        [2, 7, 4]
    ]

])
tf.size(inputTensor, out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=24.0>

In [68]:
# Random Normal Method -> Random Values Generated From A Normal Distribution Around Given Mean
normalTensor = tf.random.normal(
    [3, 2],
    mean=10.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
normalTensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 8.645584, 10.704549],
       [10.036662, 10.869188],
       [10.438423,  9.465602]], dtype=float32)>

In [81]:
# Random Uniform Method
uniformTensor = tf.random.uniform(
    [5, 2],
    minval=0,
    maxval=8, # Defaults to 1
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
uniformTensor

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[2.4943438 , 6.61073   ],
       [5.4795647 , 0.05367279],
       [6.299961  , 3.1252089 ],
       [2.3410444 , 7.937354  ],
       [7.664834  , 4.4498653 ]], dtype=float32)>

In [94]:
# Set Seed Method -> Reproducable Results
tf.random.set_seed(5)
print(tf.random.uniform([2, 3], minval=0, maxval=10, dtype=tf.int32, seed=10))
print(tf.random.uniform([2, 3], minval=0, maxval=10, dtype=tf.int32, seed=10))
print(tf.random.uniform([2, 3], minval=0, maxval=10, dtype=tf.int32, seed=10))
print(tf.random.uniform([2, 3], minval=0, maxval=10, dtype=tf.int32, seed=10))

print("\n")

tf.random.set_seed(5)
print(tf.random.uniform([2, 3], minval=0, maxval=10, dtype=tf.int32, seed=10))
print(tf.random.uniform([2, 3], minval=0, maxval=10, dtype=tf.int32, seed=10))
print(tf.random.uniform([2, 3], minval=0, maxval=10, dtype=tf.int32, seed=10))
print(tf.random.uniform([2, 3], minval=0, maxval=10, dtype=tf.int32, seed=10))

tf.Tensor(
[[9 3 6]
 [3 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 9 4]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[9 7 2]
 [7 0 8]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[4 6 0]
 [7 5 1]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[9 3 6]
 [3 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 9 4]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[9 7 2]
 [7 0 8]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[4 6 0]
 [7 5 1]], shape=(2, 3), dtype=int32)
